on: 
  push:
    branches:
      - master


name: Site Deployment

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup, Build and Install Dependencies using Node.JS
        run: npm install && npm run build && npm run deploy

