on: 
  push:
    branches:
      - master

name: Site Deployment
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup, Build and Install Dependencies using Node.JS
        run: npm install && npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages 
          FOLDER: /
          CLEAN: true # Automatically remove deleted files from the deploy branch
